spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            # Kafka broker url
            - localhost:29092
          auto-create-topics: true
        bindings:
          # Configuration for DLQ
          consumerWithErrorHandling-in-0:
           consumer:
             enable-dlq: true
             dlq-name: test-kafka-topic-with-error-handler.dlq
      default-binder: kafka
      bindings:
        # Sample consumer configuration where in stands for input while 0 is default index
        sampleConsumer-in-0:
          destination: test-kafka-topic
          group: sample-consumer-group
        # Sample Producer configuration where in-0 stands for input
        sampleProducer-in-0:
          destination: another-consumer-topic
          group: sample-producer-group
        # Sample Producer configuration where out-0 stands for output
        sampleProducer-out-0:
          destination: another-producer-topic
          group: sample-producer-group
        # DLQ configuration added for below
        consumerWithErrorHandling-in-0:
          destination: test-kafka-topic-with-error-handler
          group: sample-consumer-group
    function:
      definition: sampleConsumer;sampleProducer;consumerWithErrorHandling;
  application:
    name: kafka
server:
  port: 8085
